#!/usr/bin/env zsh

# First, make sure to install Homebrew
# from https://github.com/Homebrew/brew/releases

# Settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'
# Ask for the administrator password upfront
sudo -v
# Keep-alive: update existing `sudo` time stamp until `setup-*` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Check for potential problems.
brew doctor
# Update recipes and formulae.
brew update && brew upgrade

# Install secured password manager
brew install --cask proton-pass

# Nerd Fonts for the Terminal and the Editors.
# Once installed, you can select them in the Terminal preferences.
brew search '/font-jetbrains.*-nerd-font/' | awk '{ print $1 }' | xargs brew install

brew install fzf
brew install zoxide
brew install httpie

# Uncomment if not installed via xcode.
brew install --cask git-credential-manager
brew install gh

brew install azure-cli
brew install awscli
brew install opentofu

# Replace podman from Docker.
# See https://github.com/localstack/localstack/issues/5304
brew install --cask docker-desktop
brew install localstack/tap/localstack-cli

# Install some editors.
brew install --cask visual-studio-code
brew install --cask typora@dev
brew install --cask drawio
brew install --cask chatgpt

# Uninstalls unnecessary formulae.
brew autoremove
brew cleanup

# Manage symlinks.
# Symlink dotfiles into HOME
# Symlink instead of replacing.
# ln -sf <source> <destination>
# E.g. ln -sf ~/.dotfiles/.docker-compose ~/.docker-compose
# Use stow instead.
brew install stow
# Backup existing files.
mv ~/.zshrc ~/.zshrc.bak
mv ~/.gitconfig ~/.gitconfig.bak

stow az git gh zshrc
# FIXME: Gitignore is special for some reason.
ln -sf $(pwd)/git/.gitignore ~/.gitignore
# FIXME: VS Code is special for having global settings somewhere else.
ln -sf $(pwd)/.vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
