version: "1"
# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
# Read more at https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases
aliases:
    # List all the aliases defined below.
    # gh a
    a: alias list
    # Shows the current username ans the auth info.
    # gh whoami
    whoami: auth status -t
    # Clones a repo from GitHub.com or from an HTTP path.
    # gh c zebra-snooze
    # gh c alertbox/try-bun
    # gh c https://github.com/alertbox/zebra-snooze
    c: repo clone
    # Syncs a repo forcefully from upstream repo.
    # gh sync
    sync: repo sync --force
